export const RECIPE_LIST_REQUEST = ' RECIPE_LIST_REQUEST';
export const  RECIPE_LIST_SUCCESS = ' RECIPE_LIST_SUCCESS';
export const  RECIPE_LIST_FAIL = ' RECIPE_LIST_FAIL';

export const RECIPE_DETAILS_REQUEST = ' RECIPE_DETAILS_REQUEST';
export const  RECIPE_DETAILS_SUCCESS = ' RECIPE_DETAILS_SUCCESS';
export const  RECIPE_DETAILS_FAIL = ' RECIPE_DETAILS_FAIL';